name: fluent_regex
description: Package that helps to construct regular expressions in a readable fashion.
version: 1.0.1
homepage: https://github.com/domain-centric/fluent_regex

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1