name: fluent_regex
description: Package that helps to construct regular expressions in a readable fashion.
version: 0.0.2
homepage: https://github.com/efficientyboosters/fluent_regex

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.1
  test: 1.17.10

flutter:
